/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.parqueadero.presentacion;

/**
 * Interfaz gráfica de Registrar Parqueadero
 */
public class GUIRegistrarParqueadero extends javax.swing.JFrame {

    /**
     * Creates new form GUIRegistrarParqueadero
     */
    public GUIRegistrarParqueadero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistrarParqueaderoHead = new javax.swing.JPanel();
        lblRegistrarParqueadero = new javax.swing.JLabel();
        pnlRegistrarParqueaderoBody = new javax.swing.JPanel();
        lblInfo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        tfDireccion = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        btnRegistrarParqCancel = new javax.swing.JButton();
        btnRegistrarParqueadero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRegistrarParqueaderoHead.setBackground(new java.awt.Color(250, 152, 58));

        lblRegistrarParqueadero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRegistrarParqueadero.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrarParqueadero.setText("Registrar Parqueadero");

        javax.swing.GroupLayout pnlRegistrarParqueaderoHeadLayout = new javax.swing.GroupLayout(pnlRegistrarParqueaderoHead);
        pnlRegistrarParqueaderoHead.setLayout(pnlRegistrarParqueaderoHeadLayout);
        pnlRegistrarParqueaderoHeadLayout.setHorizontalGroup(
            pnlRegistrarParqueaderoHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarParqueaderoHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistrarParqueadero)
                .addContainerGap(356, Short.MAX_VALUE))
        );
        pnlRegistrarParqueaderoHeadLayout.setVerticalGroup(
            pnlRegistrarParqueaderoHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarParqueaderoHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistrarParqueadero)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(pnlRegistrarParqueaderoHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlRegistrarParqueaderoBody.setBackground(new java.awt.Color(10, 61, 98));
        pnlRegistrarParqueaderoBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblInfo.setText("Ingrese los datos de su parqueadero:");
        pnlRegistrarParqueaderoBody.add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre:");
        pnlRegistrarParqueaderoBody.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        tfNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlRegistrarParqueaderoBody.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 280, -1));

        lblDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccion.setText("Dirección:");
        pnlRegistrarParqueaderoBody.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        tfDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlRegistrarParqueaderoBody.add(tfDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 280, -1));

        lblTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono.setText("Telefono:");
        pnlRegistrarParqueaderoBody.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        tfTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlRegistrarParqueaderoBody.add(tfTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 280, -1));

        btnRegistrarParqCancel.setBackground(new java.awt.Color(255, 94, 87));
        btnRegistrarParqCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarParqCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarParqCancel.setText("Cancelar");
        btnRegistrarParqCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarParqCancelMouseClicked(evt);
            }
        });
        pnlRegistrarParqueaderoBody.add(btnRegistrarParqCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        btnRegistrarParqueadero.setBackground(new java.awt.Color(30, 144, 255));
        btnRegistrarParqueadero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarParqueadero.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarParqueadero.setText("Registrar");
        pnlRegistrarParqueaderoBody.add(btnRegistrarParqueadero, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        getContentPane().add(pnlRegistrarParqueaderoBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 570, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarParqCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarParqCancelMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnRegistrarParqCancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRegistrarParqueadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRegistrarParqueadero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarParqCancel;
    private javax.swing.JButton btnRegistrarParqueadero;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRegistrarParqueadero;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JPanel pnlRegistrarParqueaderoBody;
    private javax.swing.JPanel pnlRegistrarParqueaderoHead;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
